name: Build Android APK

# O robô será ativado sempre que salvarmos (push) o código na branch principal
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar Flet
        run: pip install flet
        
      - name: Instalar Java (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Instalar Flutter (Motor do Flet)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Compilar o APK
        run: flet build apk
        
      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-android
          path: build/apk/**/*.apk
